global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8889']

  - job_name: 'spring-boot-apps'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: 
        - 'host.docker.internal:8001'  # CourseApp
        - 'host.docker.internal:8002'  # CourseCatalog

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']